testing new infra

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,73 +1,107 @@
-name: CI/CD Pipeline to AWS ECS
 
-# Pipeline to deploy to ECS
-# - need to manually create Load Balancer and 2 Target groups
-# - need to upload env key json to s3. structure is [{"name": "key", "value": "SECRET"}]
-#
-# Pipeline will create ERC repo and ECS cluster. It will also create Cloudwatch log group
-# It will then build image push to ECR, create service with task definition
-# It will then create codedeploy configs as necessary
-# It will deploy code
+name: BuildInfrastructure
 
 on:
-    push:
-        branches: [cicd_new_infra]
+  push:
+    branches: [cicd_new_infra]
 
 jobs:
-    build-and-deploy:
-        name: Build and Deploy to ECS
-        runs-on: ubuntu-latest
+  build-and-deploy:
+    name: Build and Deploy to ECS
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      id-token: write
 
-        steps:
-            - name: Setup Variables for Deployment
-              run: |
-                  if [ "${{ github.ref }}" == "refs/heads/cicd_new_infra" ]; then
-                    declare -A vars=(
-                      [ECR]=mercle-mercle
-                    )
-                  fi
+    steps:
+      - name: Setup Variables for Deployment
+        run: |
+          if [ "${{ github.ref }}" == "refs/heads/cicd_new_infra" ]; then
+            declare -A vars=(
+            
+              [TASK_DEFINITION]=mercle-staging-staging_ipfs_gw
+              [CONTAINER_NAME]=mercle-staging-staging_ipfs_gateway_cluster_2
+              [CODEDEPLOY_APP_NAME]=mercle-staging-stagingipfsgatewaycontainer1-code-deploy
+              [CODEDEPLOY_GROUP_NAME]=mercle-staging-stagingipfsgatewaycontainer1-code-deploy
+              [CD_BUCKET_NAME]=mercleecscodedeploy
+              [CD_BUCKET_PATH]=ipfsGateway/staging
+            )
+            for var in "${!vars[@]}"; do
+              echo "${var}=${vars[$var]}" >> $GITHUB_ENV
+              echo "${var}=${vars[$var]}"
+            done
+          fi
+      - name: Check out code
+        uses: actions/checkout@v2
 
-                  for var in "${!vars[@]}"; do
-                    echo "${var}=${vars[$var]}" >> $GITHUB_ENV
-                    echo "${var}=${vars[$var]}"
-                  done
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ secrets.ROLE_ARN }}
+          aws-region: ${{ secrets.AWS_REGION }}
 
-            - name: Check out code
-              uses: actions/checkout@v2
+      - name: Download current ECS task definition
+        run: |
+          aws ecs describe-task-definition --task-definition $TASK_DEFINITION --region ${{ secrets.AWS_REGION }} > task-def.json
+      - name: Update task definition version and image tag
+        run: |
+          # Fetch the current task definition
+          aws ecs describe-task-definition --task-definition $TASK_DEFINITION --region ${{ secrets.AWS_REGION }} > task-def.json
+          FULL_IMAGE=670732250846.dkr.ecr.us-east-1.amazonaws.com/mercle_pi_stagging_3:73c223d706b970480db128e2e53e0bf7d4f1e6db
+          jq --arg image "$FULL_IMAGE" '.taskDefinition.containerDefinitions[0].image = $image' task-def.json > updated-task-def.json
+          jq '.taskDefinition' updated-task-def.json | jq 'del(.taskDefinitionArn, .status, .compatibilities, .requiresAttributes, .revision,.registeredAt,.registeredBy)' > updated-2-task-def.json
+          NEW_TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://updated-2-task-def.json --region ${{ secrets.AWS_REGION }} | jq -r '.taskDefinition.taskDefinitionArn')
+          echo "Registered Task Definition ARN: $NEW_TASK_DEF_ARN"
+          echo "TASK_DEF_ARN=$NEW_TASK_DEF_ARN" >> $GITHUB_ENV
+          export "TASK_DEF_ARN=$NEW_TASK_DEF_ARN"
+      - name: Debug Intermediate Task Definition Files
+        run: |
+          cat updated-2-task-def.json
+       
 
-            - name: Set up Docker Buildx
-              uses: docker/setup-buildx-action@v1
-
-            - name: Cache Docker layers
-              uses: actions/cache@v2
-              with:
-                  path: /tmp/.buildx-cache
-                  key: ${{ runner.os }}-buildx-${{ github.sha }}
-                  restore-keys: |
-                      ${{ runner.os }}-buildx-
-
-            - name: Configure AWS credentials
-              uses: aws-actions/configure-aws-credentials@v1
-              with:
-                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-                  aws-region: ap-south-1
-
-            - name: Login to Amazon ECR
-              uses: aws-actions/amazon-ecr-login@v1
-              with:
-                  mask-aws-account-id: true
-
-            - name: Build and Push Image to AWS ECR
-              uses: docker/build-push-action@v2
-              with:
-                  context: .
-                  file: ./Dockerfile
-                  push: true
-                  tags:
-                      ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/${{
-                      env.ECR}}:${{ github.sha }}
-                  build-args: |
-                      BUILDKIT_INLINE_CACHE=1
-                  cache-from: type=local,src=/tmp/.buildx-cache
-                  cache-to: type=local,dest=/tmp/.buildx-cache-new
+      - name: Install yq
+        run: |
+          # Install yq to a user-writable directory
+          mkdir -p $HOME/.local/bin
+          wget https://github.com/mikefarah/yq/releases/download/v4.20.2/yq_linux_amd64 -O $HOME/.local/bin/yq
+          chmod +x $HOME/.local/bin/yq
+          echo "$HOME/.local/bin" >> $GITHUB_PATH
+      - name: Update app specification                 
+        run: |
+          aws s3 cp s3://$CD_BUCKET_NAME/$CD_BUCKET_PATH/appspec.yaml ./appspec.yaml
+          yq eval ".Resources[0].TargetService.Properties.TaskDefinition = \"$TASK_DEF_ARN\"" appspec.yaml > updated-appspec.yaml
+          aws s3 cp ./updated-appspec.yaml s3://$CD_BUCKET_NAME/$CD_BUCKET_PATH/appspec.yaml
+      - name: Display appspec.yaml
+        run: |
+          cat appspec.yaml
+      - name: Create CodeDeploy Deployment
+        run: |
+          # Prepare deployment configuration
+          sed -e "s|<CODEDEPLOY_APP_NAME>|$CODEDEPLOY_APP_NAME|g" .ecs/create-deployment-template.json > tmp.yaml && mv tmp.yaml create-deployment.json
+          sed -e "s|<CODEDEPLOY_GROUP_NAME>|$CODEDEPLOY_GROUP_NAME|g" create-deployment.json > tmp.yaml && mv tmp.yaml create-deployment.json
+          sed -e "s|<CD_BUCKET_NAME>|$CD_BUCKET_NAME|g" create-deployment.json > tmp.yaml && mv tmp.yaml create-deployment.json
+          sed -e "s|<CD_BUCKET_PATH>|$CD_BUCKET_PATH|g" create-deployment.json > tmp.yaml && mv tmp.yaml create-deployment.json
+          # Create deployment
+          DEPLOYMENT_ID=$(aws deploy create-deployment --cli-input-json file://create-deployment.json --output json | jq -r '.deploymentId')
+          echo "Deployment started with ID: $DEPLOYMENT_ID"
+          echo "DEPLOYMENT_ID=$DEPLOYMENT_ID" >> $GITHUB_ENV
+      - name: Check Deployment Status
+        run: |
+          while true; do
+            STATUS=$(aws deploy get-deployment --deployment-id $DEPLOYMENT_ID --query 'deploymentInfo.status' --output text)
+            if [ "$STATUS" == "Succeeded" ]; then
+              echo "Deployment successful!"
+              break
+            elif [ "$STATUS" == "Failed" ]; then
+              echo "Deployment failed!"
+              exit 1
+            else
+              echo "Deployment status: $STATUS. Checking again in 30 seconds."
+              sleep 30
+            fi
+          done
+      - name: Clean up Cache
+        uses: actions/cache@v2
+        with:
+          path: /tmp/.buildx-cache-new
+          key: ${{ runner.os }}-buildx-${{ github.sha }}
